//! Session persistence DTOs — wire format for the JSONL rollout journal.
//!
//! Shape ported from `claw-code-rust/crates/core/src/conversation/records.rs`
//! adapted to elal's local-only model: no provider abstraction (the
//! "provider" is always an embedded GGUF file path), typed `ApprovalMode`
//! instead of stringly-typed, and a `model_sha256` field that pairs with
//! `LlamaContext::state_save_file` snapshots so a model swap forces re-eval
//! instead of loading a stale KV cache.
//!
//! These types are pure data: no I/O, no async. The reader (replay) and
//! writer (rollout store) live in `elal_core::session`.
//!
//! ## JSONL contract
//!
//! Each rollout file is a sequence of newline-delimited JSON objects. Every
//! line deserializes to a [`RolloutLine`]. The first line is always a
//! [`RolloutLine::SessionMeta`]. Subsequent lines are [`RolloutLine::Turn`]
//! and [`RolloutLine::Item`] in append order; [`RolloutLine::SessionTitleUpdated`]
//! lines may appear at any point after the meta line.
//!
//! Append-only — never rewrite or reorder existing lines. Atomic-overwrite
//! changes (such as session title) are mirrored as new lines.

use std::path::PathBuf;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::approval::ApprovalMode;
use crate::identifiers::{ItemId, SessionId, ToolCallId, TurnId};

/// Current schema version emitted by this crate. Bump on any breaking change
/// to the persisted JSON shape; replay tolerates older versions explicitly.
pub const SCHEMA_VERSION: u32 = 1;

/// Lifecycle status of a single turn.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TurnStatus {
    /// The turn has been created but no inference has started yet.
    Pending,
    /// Inference is in flight.
    Running,
    /// The turn finished successfully (model emitted plain text, no pending tool calls).
    Completed,
    /// The turn ended with an unrecoverable error.
    Failed,
    /// The user cancelled the turn before it reached a terminal state.
    Cancelled,
}

/// Token-usage summary captured at turn completion. All fields are zero when
/// the underlying provider does not report usage.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TurnUsage {
    /// Tokens fed to the model as prompt input for this turn.
    pub input_tokens: u64,
    /// Tokens generated by the model in response.
    pub output_tokens: u64,
    /// Cache-creation input tokens reported by upstream-cache-aware providers.
    /// Zero for embedded local inference.
    #[serde(default)]
    pub cache_creation_input_tokens: u64,
    /// Cache-read input tokens reported by upstream-cache-aware providers.
    /// Zero for embedded local inference.
    #[serde(default)]
    pub cache_read_input_tokens: u64,
}

/// Persisted metadata for one session.
///
/// Written once at session creation as the first rollout line (see
/// [`SessionMetaLine`]). Mutating fields (`updated_at`, `total_*_tokens`,
/// `title`) are tracked in memory and mirrored to a sidecar `meta.json` file
/// the rollout store maintains atomically — the JSONL itself is append-only.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionRecord {
    /// Stable session identifier.
    pub id: SessionId,
    /// Absolute path to the canonical JSONL rollout for this session.
    pub rollout_path: PathBuf,
    /// Wall-clock time at session creation.
    pub created_at: DateTime<Utc>,
    /// Wall-clock time of the most recent metadata update.
    pub updated_at: DateTime<Utc>,
    /// Source kind that created the session — typically `"cli"`.
    pub source: String,
    /// Filesystem path to the GGUF model bound to this session, when known.
    /// Required by the KV-cache snapshot path: a snapshot is only safe to
    /// load when the resuming session uses the same model file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_path: Option<PathBuf>,
    /// SHA-256 of the GGUF model file at the time of the last turn. Used by
    /// the KV-snapshot loader to refuse stale snapshots when the underlying
    /// model bytes have changed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_sha256: Option<String>,
    /// Working directory the session was opened from. Used by `--continue` to
    /// pick the most recent session matching the user's current cwd.
    pub cwd: PathBuf,
    /// Version of the `elal` binary that created the session.
    pub elal_version: String,
    /// Human-readable title, when one has been derived or set explicitly.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Approval mode the session was created under. Persisted so a `--resume`
    /// honours the user's original choice unless they override it.
    pub approval_mode: ApprovalMode,
    /// Cumulative input tokens across every completed turn.
    #[serde(default)]
    pub total_input_tokens: u64,
    /// Cumulative output tokens across every completed turn.
    #[serde(default)]
    pub total_output_tokens: u64,
    /// Verbatim first user message, retained for previews / title derivation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_user_message: Option<String>,
    /// Schema version that produced this record. Replay must tolerate older
    /// values; writers always emit [`SCHEMA_VERSION`].
    pub schema_version: u32,
}

/// Persisted metadata for one turn.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TurnRecord {
    /// Stable turn identifier.
    pub id: TurnId,
    /// Owning session.
    pub session_id: SessionId,
    /// Strictly increasing per-session turn sequence (1-based).
    pub sequence: u32,
    /// Wall-clock time at turn start.
    pub started_at: DateTime<Utc>,
    /// Wall-clock time when the turn reached a terminal state, when applicable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    /// Lifecycle status of the turn.
    pub status: TurnStatus,
    /// Filesystem path to the GGUF model used by this turn, when known.
    /// May differ from [`SessionRecord::model_path`] if the user swapped
    /// models mid-session (a swap drops any KV-cache snapshot).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_path: Option<PathBuf>,
    /// Authoritative provider token usage when the turn completed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<TurnUsage>,
    /// Schema version that produced this record.
    pub schema_version: u32,
}

/// Plain-text item payload (user message, assistant message, compaction summary).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TextItem {
    /// Verbatim textual payload.
    pub text: String,
}

/// Reasoning-content payload emitted by reasoning models (Qwen3 `<think>`,
/// DeepSeek-R1 distills). Stored separately from regular text so a future
/// renderer can hide it by default.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReasoningItem {
    /// Verbatim reasoning text, exactly as the parser surfaced it.
    pub text: String,
}

/// One tool-call request emitted by the model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolCallItem {
    /// Stable identifier issued by the model for this call.
    pub tool_call_id: ToolCallId,
    /// Runtime name of the requested tool.
    pub tool_name: String,
    /// Validated JSON input passed to the tool.
    pub input: serde_json::Value,
}

/// One terminal tool result, paired with its originating call by id.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolResultItem {
    /// Identifier of the originating tool call.
    pub tool_call_id: ToolCallId,
    /// Normalized structured output emitted by the tool.
    pub output: serde_json::Value,
    /// Whether the tool reported a soft or hard error outcome.
    pub is_error: bool,
}

/// Canonical persisted item kinds recorded for each turn.
///
/// This is the `elal` subset of `claw-code-rust`'s `TurnItem`. Items
/// owned by other subsystems (approvals: see [`crate::ApprovalDecisionValue`])
/// are intentionally not duplicated here.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum TurnItem {
    /// User-facing message originating from the human operator.
    UserMessage(TextItem),
    /// User-visible assistant response (final text, not reasoning).
    AgentMessage(TextItem),
    /// Reasoning trace emitted by the model and surfaced separately.
    Reasoning(ReasoningItem),
    /// A tool-call request issued by the model.
    ToolCall(ToolCallItem),
    /// A terminal tool-result feedback to the model.
    ToolResult(ToolResultItem),
    /// Synthetic summary inserted when older history is dropped to fit the
    /// context budget. Replay treats this as a regular system-side message.
    ContextCompaction(TextItem),
}

/// One persisted item record. Each record corresponds to a single line in the
/// JSONL rollout (wrapped in [`ItemLine`]).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ItemRecord {
    /// Stable item identifier.
    pub id: ItemId,
    /// Owning session.
    pub session_id: SessionId,
    /// Owning turn.
    pub turn_id: TurnId,
    /// Strictly increasing per-session item sequence number.
    pub seq: u64,
    /// Wall-clock time the record was persisted.
    pub timestamp: DateTime<Utc>,
    /// Items grouped under this record. Most records carry a single item;
    /// using a vector lets the writer emit a tool-call together with its
    /// invocation arguments without splitting them across two records.
    pub items: Vec<TurnItem>,
    /// Schema version that produced this record.
    pub schema_version: u32,
}

/// First line of every rollout journal — the session metadata header.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionMetaLine {
    /// Wall-clock time the line was persisted.
    pub timestamp: DateTime<Utc>,
    /// Session metadata payload.
    pub session: SessionRecord,
}

/// Turn metadata line.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TurnLine {
    /// Wall-clock time the line was persisted.
    pub timestamp: DateTime<Utc>,
    /// Turn metadata payload.
    pub turn: TurnRecord,
}

/// Item record line.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ItemLine {
    /// Wall-clock time the line was persisted.
    pub timestamp: DateTime<Utc>,
    /// Item record payload.
    pub item: ItemRecord,
}

/// Session-title change line. Title updates are append-only just like every
/// other rollout line; the in-memory current-title view is the most recent
/// non-empty title.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionTitleUpdatedLine {
    /// Wall-clock time the line was persisted.
    pub timestamp: DateTime<Utc>,
    /// Session whose title changed.
    pub session_id: SessionId,
    /// New title value.
    pub title: String,
    /// Previous title, when one existed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_title: Option<String>,
}

/// Every canonical line type written to the rollout journal.
///
/// `SessionMeta` and `CompactionSnapshot`-equivalent variants are boxed when
/// large to keep the enum size reasonable across the hot path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum RolloutLine {
    /// Session metadata header — must be the first line of every rollout.
    SessionMeta(Box<SessionMetaLine>),
    /// Turn metadata.
    Turn(TurnLine),
    /// Item record.
    Item(ItemLine),
    /// Session title change.
    SessionTitleUpdated(SessionTitleUpdatedLine),
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn fixed_ts() -> DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 4, 29, 12, 0, 0).unwrap()
    }

    fn sample_session_record() -> SessionRecord {
        SessionRecord {
            id: SessionId::new(),
            rollout_path: PathBuf::from("/tmp/elal/sessions/2026/04/foo.jsonl"),
            created_at: fixed_ts(),
            updated_at: fixed_ts(),
            source: "cli".into(),
            model_path: Some(PathBuf::from("/models/Qwen3-Coder-30B.gguf")),
            model_sha256: Some("a".repeat(64)),
            cwd: PathBuf::from("/var/mnt/DATA/Repos/elal"),
            elal_version: "0.1.0".into(),
            title: None,
            approval_mode: ApprovalMode::Smart,
            total_input_tokens: 0,
            total_output_tokens: 0,
            first_user_message: None,
            schema_version: SCHEMA_VERSION,
        }
    }

    fn sample_turn_record(session_id: SessionId) -> TurnRecord {
        TurnRecord {
            id: TurnId::new(),
            session_id,
            sequence: 1,
            started_at: fixed_ts(),
            completed_at: Some(fixed_ts()),
            status: TurnStatus::Completed,
            model_path: Some(PathBuf::from("/models/Qwen3-Coder-30B.gguf")),
            usage: Some(TurnUsage {
                input_tokens: 1024,
                output_tokens: 256,
                cache_creation_input_tokens: 0,
                cache_read_input_tokens: 0,
            }),
            schema_version: SCHEMA_VERSION,
        }
    }

    #[test]
    fn turn_status_serializes_as_snake_case() {
        assert_eq!(
            serde_json::to_string(&TurnStatus::Cancelled).unwrap(),
            "\"cancelled\""
        );
        let parsed: TurnStatus = serde_json::from_str("\"running\"").unwrap();
        assert_eq!(parsed, TurnStatus::Running);
    }

    #[test]
    fn session_record_roundtrip() {
        let record = sample_session_record();
        let json = serde_json::to_string(&record).unwrap();
        let back: SessionRecord = serde_json::from_str(&json).unwrap();
        assert_eq!(record, back);
    }

    #[test]
    fn session_record_omits_nones() {
        let mut record = sample_session_record();
        record.title = None;
        record.first_user_message = None;
        let value = serde_json::to_value(&record).unwrap();
        assert!(value.get("title").is_none(), "title must be omitted");
        assert!(
            value.get("first_user_message").is_none(),
            "first_user_message must be omitted"
        );
    }

    #[test]
    fn turn_record_roundtrip() {
        let record = sample_turn_record(SessionId::new());
        let json = serde_json::to_string(&record).unwrap();
        let back: TurnRecord = serde_json::from_str(&json).unwrap();
        assert_eq!(record, back);
    }

    #[test]
    fn turn_usage_zero_defaults() {
        let usage = TurnUsage::default();
        assert_eq!(usage.input_tokens, 0);
        assert_eq!(usage.output_tokens, 0);
        let json = serde_json::to_string(&usage).unwrap();
        let back: TurnUsage = serde_json::from_str(&json).unwrap();
        assert_eq!(usage, back);
    }

    #[test]
    fn turn_item_tagged_as_kind() {
        let item = TurnItem::UserMessage(TextItem {
            text: "hello".into(),
        });
        let value = serde_json::to_value(&item).unwrap();
        assert_eq!(value["kind"], "user_message");
        assert_eq!(value["text"], "hello");
    }

    #[test]
    fn turn_item_tool_call_roundtrip() {
        let item = TurnItem::ToolCall(ToolCallItem {
            tool_call_id: ToolCallId("call_1".into()),
            tool_name: "read".into(),
            input: serde_json::json!({"path": "Cargo.toml"}),
        });
        let json = serde_json::to_string(&item).unwrap();
        let back: TurnItem = serde_json::from_str(&json).unwrap();
        assert_eq!(item, back);
    }

    #[test]
    fn turn_item_tool_result_roundtrip() {
        let item = TurnItem::ToolResult(ToolResultItem {
            tool_call_id: ToolCallId("call_1".into()),
            output: serde_json::json!({"content": "[package]"}),
            is_error: false,
        });
        let json = serde_json::to_string(&item).unwrap();
        let back: TurnItem = serde_json::from_str(&json).unwrap();
        assert_eq!(item, back);
    }

    #[test]
    fn turn_item_reasoning_roundtrip() {
        let item = TurnItem::Reasoning(ReasoningItem {
            text: "step 1 → step 2".into(),
        });
        let json = serde_json::to_string(&item).unwrap();
        let back: TurnItem = serde_json::from_str(&json).unwrap();
        assert_eq!(item, back);
    }

    #[test]
    fn item_record_roundtrip() {
        let session_id = SessionId::new();
        let turn_id = TurnId::new();
        let record = ItemRecord {
            id: ItemId::new(),
            session_id,
            turn_id,
            seq: 7,
            timestamp: fixed_ts(),
            items: vec![
                TurnItem::AgentMessage(TextItem {
                    text: "let me check".into(),
                }),
                TurnItem::ToolCall(ToolCallItem {
                    tool_call_id: ToolCallId("call_1".into()),
                    tool_name: "list_dir".into(),
                    input: serde_json::json!({"path": "."}),
                }),
            ],
            schema_version: SCHEMA_VERSION,
        };
        let json = serde_json::to_string(&record).unwrap();
        let back: ItemRecord = serde_json::from_str(&json).unwrap();
        assert_eq!(record, back);
    }

    #[test]
    fn rollout_line_session_meta_roundtrip() {
        let line = RolloutLine::SessionMeta(Box::new(SessionMetaLine {
            timestamp: fixed_ts(),
            session: sample_session_record(),
        }));
        let json = serde_json::to_string(&line).unwrap();
        let back: RolloutLine = serde_json::from_str(&json).unwrap();
        assert_eq!(line, back);
    }

    #[test]
    fn rollout_line_turn_roundtrip() {
        let session_id = SessionId::new();
        let line = RolloutLine::Turn(TurnLine {
            timestamp: fixed_ts(),
            turn: sample_turn_record(session_id),
        });
        let json = serde_json::to_string(&line).unwrap();
        let back: RolloutLine = serde_json::from_str(&json).unwrap();
        assert_eq!(line, back);
    }

    #[test]
    fn rollout_line_title_update_roundtrip() {
        let line = RolloutLine::SessionTitleUpdated(SessionTitleUpdatedLine {
            timestamp: fixed_ts(),
            session_id: SessionId::new(),
            title: "fix grammar bug".into(),
            previous_title: Some("untitled".into()),
        });
        let json = serde_json::to_string(&line).unwrap();
        let back: RolloutLine = serde_json::from_str(&json).unwrap();
        assert_eq!(line, back);
    }

    #[test]
    fn rollout_line_kind_tag_present() {
        let line = RolloutLine::Turn(TurnLine {
            timestamp: fixed_ts(),
            turn: sample_turn_record(SessionId::new()),
        });
        let value = serde_json::to_value(&line).unwrap();
        assert_eq!(value["kind"], "turn");
    }

    #[test]
    fn jsonl_appendability_simulated() {
        // Three rollout lines serialized one per line and parsed back in order
        // — ensures no embedded newline, no array wrapper.
        let session_id = SessionId::new();
        let lines = vec![
            RolloutLine::SessionMeta(Box::new(SessionMetaLine {
                timestamp: fixed_ts(),
                session: sample_session_record(),
            })),
            RolloutLine::Turn(TurnLine {
                timestamp: fixed_ts(),
                turn: sample_turn_record(session_id),
            }),
            RolloutLine::Item(ItemLine {
                timestamp: fixed_ts(),
                item: ItemRecord {
                    id: ItemId::new(),
                    session_id,
                    turn_id: TurnId::new(),
                    seq: 1,
                    timestamp: fixed_ts(),
                    items: vec![TurnItem::UserMessage(TextItem { text: "hi".into() })],
                    schema_version: SCHEMA_VERSION,
                },
            }),
        ];

        let serialized: Vec<String> = lines
            .iter()
            .map(|l| serde_json::to_string(l).expect("serialize"))
            .collect();
        for s in &serialized {
            assert!(!s.contains('\n'), "rollout lines must be single-line JSON");
        }
        let restored: Vec<RolloutLine> = serialized
            .iter()
            .map(|s| serde_json::from_str(s).expect("deserialize"))
            .collect();
        assert_eq!(lines, restored);
    }
}
