[package]
name = "elal_tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
crossterm     = { workspace = true }
ratatui       = { workspace = true }
tracing       = { workspace = true }
unicode-width = { workspace = true }

[dev-dependencies]
vt100 = "0.16"
