[package]
name = "oma_cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "oma"
path = "src/main.rs"

[features]
default = ["vulkan"]
vulkan  = ["oma_provider/vulkan", "oma_models/vulkan"]
rocm    = ["oma_provider/rocm", "oma_models/rocm"]
dual    = ["oma_provider/dual", "oma_models/dual"]

[dependencies]
clap               = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow             = { workspace = true }

oma_core     = { workspace = true }
oma_protocol = { workspace = true }
oma_provider = { workspace = true, default-features = false }
oma_models   = { workspace = true, default-features = false }
oma_tools    = { workspace = true }
oma_tui      = { workspace = true }

chrono     = { workspace = true }
dirs       = { workspace = true }
serde_json = { workspace = true }
uuid       = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
