[package]
name = "oma_tools"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oma_protocol = { workspace = true }

async-trait   = { workspace = true }
globwalk      = { workspace = true }
grep-matcher  = { workspace = true }
grep-regex    = { workspace = true }
grep-searcher = { workspace = true }
htmd          = { workspace = true }
reqwest       = { workspace = true }
scraper       = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
similar       = { workspace = true }
thiserror     = { workspace = true }
tokio         = { version = "1", default-features = false, features = ["sync", "process", "time", "macros", "rt"] }
tracing       = { workspace = true }
walkdir       = { workspace = true }

[dev-dependencies]
httpmock = { workspace = true }
tempfile = { workspace = true }
tokio    = { workspace = true }
